### ISSUE TITLE
deploy_formgrade fails

### ISSUE THREAD

**Issue by marcinofulus** [jupyterhub/jupyterhub-deploy-teaching#44]
nbgrader exits with (in logs):

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'hub_authenticator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py", line 526, in get
    value = obj._trait_values[self.name]
KeyError: 'hubapi_base_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/nbgrader", line 9, in <module>
    load_entry_point('nbgrader', 'console_scripts', 'nbgrader')()
  File "/tmp/src/nbgrader/nbgrader/apps/nbgraderapp.py", line 258, in main
    NbGraderApp.launch_instance()
..............................

**Comment by ellisonbg** [comment]
We have confirmed this bug and are working on it. Sorry about the problem. We have also been doing many other updates, so everything in this repo should be back to working soon.

**Comment by ellisonbg** [comment]
The architecture of formgrade has change so this is no longer relevant. Working to update the docs to reflect this as well.
